"""add_project_column

Revision ID: be57e6b29aef
Revises: c7fde44eb643
Create Date: 2026-06-16 18:53:24.697462
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be57e6b29aef'
down_revision: Union[str, None] = 'c7fde44eb643'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('project', sa.String(length=255), nullable=True, comment='Project identifier (e.g. repo name or path)'))
    op.create_index(op.f('ix_sessions_project'), 'sessions', ['project'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sessions_project'), table_name='sessions')
    op.drop_column('sessions', 'project')
    # ### end Alembic commands ###
