"""add_embedding_column

Revision ID: c7fde44eb643
Revises: a717f0080469
Create Date: 2026-06-16 18:29:41.781939
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7fde44eb643'
down_revision: Union[str, None] = 'a717f0080469'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contexts', sa.Column('embedding', sa.ARRAY(sa.Float()), nullable=True, comment='384-dim vector embedding'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contexts', 'embedding')
    # ### end Alembic commands ###
